services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
      - REDIS_URL=redis://redis:6379/0
